### ISSUE TITLE
Error with Drupal 10 / Symfony 6

### ISSUE THREAD

**Issue by dwoods** [amazeeio/drupal-integrations#10]
When doing a 'lando pull' and probably other operations on a Drupal 10 site, it's throwing the following error: 

`Uncaught TypeError: Symfony\Component\Process\Process::__construct(): Argument #1 ($command) must be of type array, string given, called in /app/drush/Commands/contrib/drupal_integrations/src/LagoonCommands.php on line 194 and defined in /app/vendor/symfony/process/Process.php:143`

It looks like Symfony Process(string) was changed to Process(array).  After checking it appears this new signature was intruduced in Symfony 3.4, but recent versions must have removed the old syntax.

PR coming with a fix.

**Comment by tobybellwood** [comment]
Looks like it came in symfony 4.2 - https://github.com/symfony/symfony/pull/27821 - this would mean it's only available in Drupal 9 - we will need to look at how to treat any b/c

**Comment by dwoods** [comment]
Updated the PR with a check for the Symfony version, I wonder if that is a good solution for b/c?  Tested on D10 but not D9 or D8 yet

**Comment by tobybellwood** [comment]
fixed in #11 #12 and #19
