### ISSUE TITLE
Support for Drush 11

### ISSUE THREAD

**Issue by Leksat** [amazeeio/drupal-integrations#7]
After upgrade to Drush 11 we got this:
```
$ drush la
PHP Fatal error:  Uncaught Error: Call to undefined function Drush\Commands\drupal_integrations\drush_cache_get() in /app/apps/cms/drush/Commands/contrib/drupal_integrations/src/LagoonCommands.php:195
```

The `drush_cache_get` function was removed in Drush 11: https://github.com/drush-ops/drush/pull/4965

**Comment by tobybellwood** [comment]
I've got the PR in to remove the cache completely - you can also set the `LAGOON_IGNORE_DRUSHCACHE` env to TRUE to ignore the cache setting.
https://github.com/amazeeio/drupal-integrations/blob/master/src/LagoonCommands.php#L197

**Comment by Leksat** [comment]
Sorry, I had no time to look into it. But the changes look safe 🤞 😄

**Comment by tobybellwood** [comment]
Ha, no worries, I tested and released it!
